<style>

</style>
<div class="pageInfo">
     <h1>Add User</h1>
</div>
<!-- widget -->
<div class="widget">
     <div class="formWrap">
     <?php 
	     $form = $this->form;
	     $form->setAttribute('action', BASE_URL.'/admin/users/add')->prepare();
	     
	     echo $this->form()->openTag($form);
	     
	     $user = $form->get('user');
	     
	     echo $this->formRow($user->get('fld_name'));
	     echo $this->formRow($user->get('email'));
	     echo $this->formRow($user->get('password'));
	     echo $this->formRow($user->get('confirm_password'));
	     echo $this->formRow($user->get('phone'));
	     echo $this->formCollection($user->get('roles'));
	     echo $this->formHidden($form->get('csrf'));
	     echo $this->formRow($form->get('submit'));
	     echo $this->formRow($form->get('cancel'));
	     echo $this->form()->closeTag();
     ?>
    </div>
</div>