<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bmsbackend\Module'                        => __DIR__ . '/Module.php',
    'Bmsbackend\Controller\IndexController' => __DIR__ . '/src/Bmsbackend/Controller/IndexController.php',
    'BmsbackendTest\Framework\TestCase'        => __DIR__ . '/tests/Bmsbackend/Framework/TestCase.php',
    'BmsbackendTest\SampleTest'                => __DIR__ . '/tests/Bmsbackend/SampleTest.php',
);
